imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

liip_functional_test: ~
nelmio_api_doc: 
  name: Hangman API
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname:   "hangman_test"

web_profiler:
    toolbar: false
    intercept_redirects: false

